import SwiftUI

// All `Color.svXxx` tokens are auto-generated by Xcode from the Asset Catalog
// (ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS = YES).
// Add a new `*.colorset` under Assets.xcassets/Colors/ to introduce a new token.
// This file exists as a discovery anchor — search "svPrimary" lands here.
//
// Available tokens (each has light + dark variants where appropriate):
//   Color.svPrimary           pink primary brand
//   Color.svPrimaryPressed    pressed-state pink
//   Color.svOnPrimary         text/icon on primary surfaces
//   Color.svBackground        screen background
//   Color.svSurface           card / sheet surface
//   Color.svOnBackground      primary text
//   Color.svSecondary         secondary text / placeholders
//   Color.svError             error text and indicators
//   Color.svDivider           hairline dividers
//   Color.svShimmer           skeleton / placeholder fill
//   Color.svFieldBackground   text-field background
//   Color.svPrimarySurface        subtle pink tint for row/card backgrounds
//   Color.svPrimarySurfaceStrong  stronger pink tint for icon badge backgrounds
//
